# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'then-snapkit-rxswift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for then-snapkit-rxswift

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'Then'
  pod 'SnapKit'

end
